kubernetesClusterDomain: cluster.local
nginx:
  ports:
  - name: web
    port: 80
    targetPort: 0
  type: ClusterIP
web:
  nginx:
    image:
      repository: registry.k8s.io/nginx-slim
      tag: "0.8"
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 250m
  volumeClaims:
    myvolume:
      requests:
        storage: 1Gi
