apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-nginx
  labels:
    app: nginx
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.type }}
  selector:
    app: nginx
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.nginx.ports | toYaml | nindent 2 -}}